# Generated by Django 3.1.4 on 2021-07-10 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='title', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
