# Generated by Django 3.1.5 on 2021-07-11 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_text',
            field=models.CharField(default='title text', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 10, 7, 30, 895535, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
