# Generated by Django 3.1.5 on 2021-07-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210711_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='no author', max_length=20),
            preserve_default=False,
        ),
    ]
