# Generated by Django 3.1.4 on 2021-07-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
